# -*- coding: utf-8 -*-
"""KHDL_practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qb3mmYArgC2X-YMkiqGRDqH8qEfcqO_9

[docs](https://www.datacamp.com/tutorial/recommender-systems-python) <br>

# Loading dataset
"""

import numpy as np
import pandas as pd
import scipy
import gdown
import zipfile

gdown.download('https://drive.google.com/uc?id=1UPHCJPnJ3DyN4exFDKo2R2_mWclRpuWx', 'dataset.zip', quiet=False)
with zipfile.ZipFile('dataset.zip', 'r') as zip_ref:
    zip_ref.extractall('dataset')

rating_df = pd.read_csv('dataset/animelist.csv',
                        usecols=["user_id", "anime_id", "rating"]
                        )
rating_df

"""# Data visualization"""

anime_df = pd.read_csv('dataset/anime.csv')
anime_df = anime_df.sort_values(by=['MAL_ID'])
anime_df

"""# Collaborative filtering

## Create rating embedding
"""

rating_df = pd.read_csv('dataset/animelist.csv',
                        low_memory=True,
                        usecols=["user_id", "anime_id", "rating"]
                        )
rating_df.head(4)

rating_df = rating_df.loc[rating_df['rating'] != 0]
rating_df

# @title
import pandas as pd
import numpy as np
from scipy.sparse import coo_matrix
import time

# cython version actual beats this in many cases, surprisingly
def pivot_sparse(df, index, columns, values, fill_value=None, dropna_idxcol=True, as_pd=True):
    """
    Summary:
        Uses scipy.sparse.coo_matrix to construct a pivot table.
        This uses less memory and is faster in most cases when the resulting pivot_table will be sparse.
        Aggregates by sum. Less functionality overall, but efficient for its usecase.

    Arguments:
        df (pandas dataframe)
        index (string or list): name(s) of column(s) that you want to become the index of the pivot table.
        columns (string or list): name(s) of column(s) that contains as values the columns of the pivot table.
        values (string): name of column that contains as values the values of the pivot table.
        fill_value (scalar, default None): value to replace missing values with in the pivot table.
        dropna_idxcol (bool, default True): if True rows where the passed index or column contain NaNs will be dropped.
            if False, NaN will be given its own index or column when appropriate.
        as_pd (bool, default True): if True returns pandas dataframe. if false, returns the scipy coo matrix (unaggregated),
            the index array, and the column array separately. In this case, fill_value is ignored

    Returns:
        pivot_df (pandas dataframe)
        ---OR---
        coo (scipy coo matrix): unaggregated.
        idx_labels (pandas index or multiindex): contains distinct index values for pivot table.
        col_labels (pandas index or multiindex): contains distinct column values for pivot table.
            if the coo matrix contains a value at pair (i, j) then the index label is idx_labels[i] and the column label
            is col_labels[j].
    """

    # tick = time.perf_counter()
    assert isinstance(index, str) or isinstance(index, list)
    assert isinstance(columns, str) or isinstance(columns, list)
    if isinstance(index, str):
        if dropna_idxcol:
            df = df.dropna(subset=[index])
    if isinstance(index, list):
        if dropna_idxcol:
            df = df.dropna(subset=index)
        if len(index) == 1:
            index = index[0]
    if isinstance(columns, str):
        if dropna_idxcol:
            df = df.dropna(subset=[columns])
    if isinstance(columns, list):
        if dropna_idxcol:
            df = df.dropna(subset=columns)
        if len(columns) == 1:
            columns = columns[0]

    if isinstance(index, str):
        #tick1 = time.perf_counter()
        idx_arr, idx_arr_unique = df[index].factorize(sort=True, use_na_sentinel=False)
        #print('factorize idx', time.perf_counter() - tick1)
    else: #TODO: any speedup here?
        #tick1 = time.perf_counter()
        idx_arr, idx_arr_unique = pd.MultiIndex.from_frame(df[index]).factorize(sort=True, use_na_sentinel=False)
        idx_arr_unique = pd.MultiIndex.from_tuples(idx_arr_unique, names=index)
        #print('factorize idx', time.perf_counter() - tick1)
    if isinstance(columns, str):
        #tick1 = time.perf_counter()
        col_arr, col_arr_unique = df[columns].factorize(sort=True, use_na_sentinel=False)
        #print('tuple conversion col', time.perf_counter() - tick1)
    else: #TODO: any speedup here?
        #tick1 = time.perf_counter()
        col_arr, col_arr_unique = pd.MultiIndex.from_frame(df[columns]).factorize(sort=True, use_na_sentinel=False)
        col_arr_unique = pd.MultiIndex.from_tuples(col_arr_unique, names=columns)
        #print('factorize col', time.perf_counter() - tick1)
    # print('prepare index and columns', time.perf_counter() - tick)

    # tick = time.perf_counter()
    coo = coo_matrix((df[values], (idx_arr, col_arr)), shape=(idx_arr_unique.shape[0], col_arr_unique.shape[0]))
    # print('coo', time.perf_counter() - tick)

    #print(coo.toarray().shape)
    #print(coo.toarray())

    if as_pd:
        # tick = time.perf_counter()
        pivot_df = pd.DataFrame.sparse.from_spmatrix(coo, index=idx_arr_unique, columns=col_arr_unique)
        pivot_df.index.rename(index, inplace=True)
        pivot_df.columns.rename(columns, inplace=True)
        #pivot_df = pd.DataFrame(coo.toarray(), index=idx_arr_unique, columns=col_arr_unique)
        # print('from_spmatrix', time.perf_counter() - tick)

        if fill_value is not None and fill_value is not np.nan:
            # tick = time.perf_counter()
            pivot_df = pivot_df.fillna(fill_value)
            # print('fillna', time.perf_counter() - tick)

        return pivot_df

    else:

        return coo, idx_arr_unique, col_arr_unique

rating_matrix = pivot_sparse(rating_df, values='rating', index=['anime_id'], columns=['user_id'], as_pd=False)
rating_matrix

from google.colab import drive
drive.mount('/content/drive')

np.save('/content/drive/MyDrive/datasets/recommendation_system/anime/anime_index.npy', rating_matrix[1].values)

rating_embedding = rating_matrix[0].tocsr().astype('float64')

scipy.sparse.save_npz("/content/drive/MyDrive/datasets/recommendation_system/anime/anime_rating_embedding.npz", rating_embedding)

"""## Create rating cosine"""

from google.colab import drive
drive.mount('/content/drive')

rating_embedding = scipy.sparse.load_npz("/content/drive/MyDrive/datasets/recommendation_system/anime/anime_rating_embedding.npz")

row_sums = ((rating_embedding.multiply(rating_embedding)).sum(axis=1))
rows_sums_sqrt = np.array(np.sqrt(row_sums))[:,0]
row_indices, col_indices = rating_embedding.nonzero()
rating_embedding.data /= rows_sums_sqrt[row_indices]
rating_cosine = rating_embedding * rating_embedding.transpose()

rating_cosine = rating_cosine.toarray()

np.save('/content/drive/MyDrive/datasets/recommendation_system/anime/anime_rating_cosine.npy', rating_cosine)

rating_cosine = np.load('/content/drive/MyDrive/datasets/recommendation_system/anime/anime_rating_cosine.npy')

rating_cosine.shape

"""## Item data mining"""

from google.colab import drive
drive.mount('/content/drive')

anime_index = np.load('/content/drive/MyDrive/datasets/recommendation_system/anime/anime_index.npy')

anime_df = pd.read_csv('dataset/anime.csv')
anime_df = anime_df.loc[anime_df['MAL_ID'].isin(anime_index)]
anime_df = anime_df.sort_values(by=['MAL_ID'])
anime_df = anime_df[['MAL_ID', 'Genres', 'Producers', 'Studios', 'Source']]
anime_df

anime_synopsis_df = pd.read_csv('dataset/anime_with_synopsis.csv')
anime_synopsis_df = anime_synopsis_df[['MAL_ID', 'sypnopsis']]
anime_synopsis_df

anime_df = pd.merge(anime_df, anime_synopsis_df, on='MAL_ID', how='left')
anime_df

anime_df = anime_df.fillna('')
anime_df.info()

anime_meta_df = anime_df[['MAL_ID', 'Genres', 'Producers', 'Studios', 'Source']]
anime_sypnopsis_df = anime_df[['MAL_ID', 'sypnopsis']]

"""### Anime metadata mining"""

features = ['Genres', 'Producers', 'Studios']

for feature in features:
    anime_meta_df[feature] = anime_meta_df[feature].apply(lambda x: x.split(','))

anime_meta_df

def clean_data(x):
    if isinstance(x, list):
        return [str.lower(i.replace(" ", "")) for i in x]
    else:
        #Check if director exists. If not, return empty string
        if isinstance(x, str):
            return str.lower(x.replace(" ", ""))
        else:
            return ''

features = ['Genres', 'Producers', 'Studios', 'Source']

for feature in features:
    anime_meta_df[feature] = anime_meta_df[feature].apply(clean_data)

anime_meta_df

def create_soup(x):
    return ' '.join(x['Genres']) + ' ' + ' '.join(x['Producers']) + ' ' + ' '.join(x['Studios']) + ' ' + x['Source']

anime_meta_df['soup'] = anime_meta_df.apply(create_soup, axis=1)
anime_meta_df

from sklearn.feature_extraction.text import CountVectorizer

meta_count_embed_matrix = CountVectorizer(stop_words='english').\
                            fit_transform(anime_meta_df['soup']).astype('float64')
meta_count_embed_matrix.shape

row_sums = ((meta_count_embed_matrix.multiply(meta_count_embed_matrix)).sum(axis=1))
rows_sums_sqrt = np.array(np.sqrt(row_sums))[:,0]
row_indices, col_indices = meta_count_embed_matrix.nonzero()
meta_count_embed_matrix.data /= rows_sums_sqrt[row_indices]
meta_cosine = meta_count_embed_matrix * meta_count_embed_matrix.transpose()

meta_cosine = meta_cosine.toarray()

"""### Content mining"""

from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_matrix = TfidfVectorizer(stop_words='english').fit_transform(anime_sypnopsis_df['sypnopsis'])
tfidf_matrix.shape

content_cosine = tfidf_matrix * tfidf_matrix.transpose()

content_cosine = content_cosine.toarray()

rating_cosine = np.load('/content/drive/MyDrive/datasets/recommendation_system/anime/anime_rating_cosine.npy')

weight_cosine = rating_cosine + meta_cosine + content_cosine
weight_cosine

np.save('/content/drive/MyDrive/datasets/recommendation_system/anime/weight.npy', weight_cosine)

weight_cosine.shape

"""## Build Agent"""

import numpy as np
import pandas as pd
import scipy
import os
import gdown
import zipfile

class Agent():
    def __init__(self, dataset_path='dataset', weight_path='weight', download_dataset=True, download_weight=True):

        if not os.path.exists(dataset_path) and download_dataset:
            gdown.download('https://drive.google.com/uc?id=1UPHCJPnJ3DyN4exFDKo2R2_mWclRpuWx', 'dataset.zip', quiet=False)
            with zipfile.ZipFile('dataset.zip', 'r') as zip_ref:
                zip_ref.extractall(dataset_path)

        if not os.path.exists(weight_path) and download_weight:
            os.mkdir(weight_path)
            gdown.download('https://drive.google.com/uc?id=1guGze0nCE8i0JPOzlToW_CzBQhUk_2-x', weight_path + '/weight.npy', quiet=False)
            gdown.download('https://drive.google.com/uc?id=1a2V11vnThZjZrdfj9t7xXCPL65MyeK6h', weight_path + '/anime_index.npy', quiet=False)

        self.weight = np.load(weight_path + '/weight.npy')
        self.anime_index = np.load(weight_path + '/anime_index.npy')
        self.anime_df = pd.read_csv(dataset_path + '/anime.csv')
        self.anime_df = self.anime_df.loc[self.anime_df['MAL_ID'].isin(self.anime_index)]
        self.anime_df = self.anime_df.sort_values(by=['MAL_ID'])

    def act(self, id: int = None, name: str = None, k=10, return_df=False):
        if isinstance(id, int):
            index = self.anime_df[self.anime_df.MAL_ID == id].index[0]
        elif isinstance(name, str):
            index = self.anime_df[self.anime_df.Name == name].index[0]
        else: raise Exception('id or name arguments not suitable, type(id) is int or type(name) is str')

        index_res = (-self.weight[index]).argsort()[:k]

        if return_df: return self.anime_df.loc[index_res]

        if isinstance(id, int):
            return self.anime_df.loc[index_res].MAL_ID.tolist()
        return self.anime_df.loc[index_res].Name.tolist()

def cus_func(m: int = 2):
    print(m)
cus_func('a')

a1 = 0
a1 is not None

Agent()

agent = Agent()

agent.weight.shape

agent.weight

agent.anime_df

agent = Agent()

agent.act(name='Naruto', k=12, return_df=True)

agent.anime_df[agent.anime_df.Name == 'Trigun'].index[0]

agent.act(name='Dragon Ball Z', k=32)

agent.act(name='Dragon Ball Z', k=32, return_df=True)

agent.weight[2].shape

agent.weight[2]

agent.weight[2][811]

a1 = (-agent.weight[2]).argsort()[:10]
a1

agent.anime_df.loc[a1].MAL_ID

agent.anime_df.loc[a1].MAL_ID.tolist()

agent.anime_index